apiVersion: apps/v1
kind: Deployment
metadata:
    name: goapp
spec:
    selector:
        matchLabels:
            app: goapp
    replicas: 2
    template:
        metadata:
            labels:
                app: goapp
        spec:
            containers:
                - name: goapp-server
                  imagePullPolicy: Never
                  image: muthiah123456789/simple-go-server:latest
                  resources:
                      limits:
                          cpu: 50m
                          memory: 100Mi
                      requests:
                          cpu: 25m
                          memory: 10Mi
                  ports:
                      - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
    name: goapp
spec:
    type: NodePort
    selector:
        app: goapp
    ports:
        - port: 5000
          targetPort: 5000
